### ISSUE TITLE
Popup blur not working correctly / is missing

### ISSUE THREAD

**Issue by Blackstonecoden** [PL7963/Discord-Mica#6]
![image](https://github.com/user-attachments/assets/3d3c18d0-60fa-4baa-ae74-0a98ad07c5df)
![image](https://github.com/user-attachments/assets/5fdcb5ef-7447-465c-b0d7-38a6eecb424b)
![image](https://github.com/user-attachments/assets/07932ea6-432e-41fc-90fe-0816d1c7f86b)
![image](https://github.com/user-attachments/assets/cc1f8d7e-6d0b-4751-b871-0cf2ec1697d8)

**Comment by PL7963** [comment]
I removed most transparent popup because Chromium/electron cannot handle the blur effect with transparent window properly. It has mentioned in #1. I'll added it back right after Chromium patched this.  
The third picture is the one I missed. I'll patch it later :)

**Comment by Blackstonecoden** [comment]
K thx ❤️

**Comment by PL7963** [comment]
> K thx ❤️ , when can we expect Chromium to patch this?

I'm not sure about that. It's been like this for over an year 😓

**Comment by PL7963** [comment]
Resolved https://github.com/PL7963/Discord-Mica/commit/e90fd74e19aac5fe5c740831b3506bd47cf3ac74
